### ISSUE TITLE
CPU Frequency sampling some times causes freeze

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#246] opened 2015-11-11 20:18 UTC
I think it might be related to #186 - or even the very same, but I'm not sure, and would like to find the root cause.

**Comment by fwsGonzo** [comment] 2016-08-16 11:24
Have yet to see this happen again recently, and we are all using different machines with different setups. Closing this for now.

**Closed by fwsGonzo** 2016-08-16 11:24 UTC
Labels: Bug

**Comment by sarum90** [comment] 2016-09-23 14:58
I might have a reproduction of this bug. Although... not sure that it's one that you care about, my development environment is a bit silly.

I have a windows computer, but I do all of my development inside a virtualbox VM running ubuntu. Thus, I think I might actually be getting binary translation when I run the VM, but qemu is very good at that, so it's not unusably slow.

If (and only if) I use grub to boot my service, then it errors out in a manner that appears as if it might be related to this.

Poor man's script to boot an IncludeOS service named IncludeOS_service using grub2 (assuming it's installed on the computer):

```
#!/bin/bash

make
mkdir -p mkdisk
rm mkdisk/disk.raw
touch mkdisk/disk.raw
truncate -s100M mkdisk/disk.raw

LO=$(losetup -f)

losetup $LO mkdisk/disk.raw

mkfs.fat $LO

mount $LO /mnt

cp -r boot /mnt/
cp IncludeOS_service /mnt/boot/

grub-install --force --boot-directory /mnt/boot/ $LO

umount $LO

losetup -d $LO


qemu-system-i386 -drive file=mkdisk/disk.raw,format=raw,if=ide -device virtio-net,netdev=net0,mac=c0:01:0a:00:00:2a -netdev tap,id=net0,script=/home/marcus/IncludeOS_install/etc/qemu-ifup -nographic -smp 4 -m 128 -k en-us
```

Assuming `boot` is a directory with a subdirectory named `grub` which has a file `grub.cfg` where `boot/grub/grub.cfg` contains:

```
set default="0"
set timeout=5
serial --unit=0 --speed=9600
terminal_input serial; terminal_output serial

menuentry IncludeOS_service {
  multiboot /boot/IncludeOS_service
}
```

When I run the above commands I get the following output consistently, which seems like it might be related to this:
[output.txt](https://github.com/hioa-cs/IncludeOS/files/489971/output.txt)

**Comment by sarum90** [comment] 2016-09-23 15:06
Eh... never mind I think it's actually something else... I commented out the line this bug concerns and it still keeps auto crashing halfway through boot.

I vaguely recall grub having some mechanism that it uses to determine if a boot was successful, and that it kills the machine if that mechanism fails... Wonder if I can actually figure out if that mechanism exists, and if it can be turned off.

**Comment by fwsGonzo** [comment] 2016-09-23 15:10
It definitely could be, as the CPU freq measuring is the first time in the boot sequence where things take time.. The rest of the boot is barely a few micros.

**Comment by sarum90** [comment] 2016-09-23 15:18
Actually now I'm thinking it actually does have something to do with the interaction with the PIT.

I commented out the first line, and then it got as far as measuring the APIC timer and would reboot again. Commented out the measuring of the APIC timer and I actually got to the point of booting (although, with everything I commented out timers did not actually work).

At this point though I have a `disk.raw` that boots with grub, and at least outputs something over the serial port once it is up and running.

**Comment by fwsGonzo** [comment] 2016-09-23 15:21
Yes, both cpufreq and APIC timer uses PIT :) Guess something funky is going on there

**Comment by fwsGonzo** [comment] 2016-09-23 15:23
Im going to the conference center now.. if you are there we could have a look :D

**Comment by sarum90** [comment] 2016-09-23 16:07
Yea! Sorry, I also was just heading out to the conference. I'm in the back of the main hall for both talks this morning.

**Comment by sarum90** [comment] 2016-09-23 17:09
Okay narrowing down on this: It seems that after the OS::halt in calculate_cpu_frequency, grub just starts again. I've never actually dealt with what x86 does after a halt before, so I guess I'm off to do some intel manual reading and/or code grepping to figure out next steps.

**Comment by sarum90** [comment] 2016-09-26 14:59
Okay for future people who find this bug:

CPU frequency sampling is the first time that IncludeOS requires interrupts to be working in order to make forward progress (if using multiboot, at the time of this writing).

Therefore, if you came across a comment that lead you to this issue, it might just be indicative of interrupts not working correctly on your boot for some unknown reason.  (For me it was because the IDT had entries that assumed segment 0x8 was executable, and the GDT that was set up by grub had segment 0x8 as a null descriptor. After modifying the GDT to have more IncludeOS friendly content, I could boot past the comment in the code that leads to this issue.)
