### ISSUE TITLE
[fixed] ACPI shutdown fail when using Serial

### ISSUE THREAD

**Issue by Voultapher** [hioa-cs/IncludeOS#987] opened 2016-12-08 23:12 UTC
This code **sometimes** results in ACPI shutdown failure.

```cpp
#include <os>
#include <hw/serial.hpp>
#include <timers>

void Service::start(const std::string&)
{
	auto& com = hw::Serial::port<1>();

	Timers::oneshot(std::chrono::seconds(3),
		[](auto) -> void { OS::shutdown(); }
	);
}
```

**Comment by fwsGonzo** [comment] 2016-12-09 00:25
Have you checked if the Serial object here isn't being optimized away?

**Comment by Voultapher** [comment] 2016-12-09 12:11
`volatile auto& com = hw::Serial::port<1>();` does the same.
And just `OS::shutdown` did never fail.

**Comment by gurka** [comment] 2017-01-26 19:35
Has this been fixed? I'm not able to reproduce it on IncludeOS v0.10.0-rc.1-9-g151a2b9.

What exactly did you mean with "ACPI shutdown fail"?  Did you get some kind of error message or was the machine not just shutting down?

**Comment by Voultapher** [comment] 2017-01-27 11:57
It printed "ACPI shutdown fail" [relevant code](https://github.com/hioa-cs/IncludeOS/blob/dev/src/hw/acpi.cpp#L358)

Although this example may not fail anymore, it still occurs on other occasions.

**Comment by fwsGonzo** [comment] 2017-02-04 19:19
Is this still happening?

**Comment by Voultapher** [comment] 2017-02-05 08:42
Seems to be fixed.

**Comment by Voultapher** [comment] 2017-02-05 08:48
Can we tag it as fixed and then close it.

**Comment by fwsGonzo** [comment] 2017-02-05 11:15
Not sure how to tag something as fixed, but it has to have been happening because of something else... Closing :P

**Closed by fwsGonzo** 2017-02-05 11:15 UTC
Labels: Bug
