### ISSUE TITLE
Multiple duplicate "Other Bridge" entries in boot output on VMWare

### ISSUE THREAD

**Issue by ingve** [hioa-cs/IncludeOS#1281] opened 2017-03-31 08:57 UTC
```
[...]
[ PCI Manager ] Probing PCI bus
                |
                +--+ Host Bridge (0x0)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ ISA Bridge (0x1)
                |
                +--+ Mass Storage Controller 
                [ Resource @ BAR 4 ]
                  Address:  0x1060 Size: 0x10
                  Type: IO Resource
                
                |  +--+ Driver: Not found
                |
                +--+ Other Bridge (0x80)
                |
                +--+ Base system peripherals 
                [ Resource @ BAR 0 ]
                  Address:  0x1080 Size: 0x40
                  Type: IO Resource
                [ Resource @ BAR 1 ]
                  Address:  0xfebfe000 Size: 0x2000
                  Type: Memory Resource
                
                |
                +--+ Display Controller 
                [ Resource @ BAR 0 ]
                  Address:  0x1070 Size: 0x10
                  Type: IO Resource
                [ Resource @ BAR 1 ]
                  Address:  0xe8000000 Size: 0x8000000
                  Type: Memory Resource
                [ Resource @ BAR 2 ]
                  Address:  0xfe000000 Size: 0x800000
                  Type: Memory Resource
                
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Multimedia Controller 
                [ Resource @ BAR 0 ]
                  Address:  0x2000 Size: 0x40
                  Type: IO Resource
                
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Ethernet Network Controller (0x0)
                [ Resource @ BAR 0 ]
                  Address:  0xfd5fc000 Size: 0x1000
                  Type: Memory Resource
                [ Resource @ BAR 1 ]
                  Address:  0xfd5fd000 Size: 0x1000
                  Type: Memory Resource
                [ Resource @ BAR 2 ]
                  Address:  0xfd5fe000 Size: 0x2000
                  Type: Memory Resource
                [ Resource @ BAR 3 ]
                  Address:  0x4000 Size: 0x10
                  Type: IO Resource
                
                |  +--+ Driver: Found
    [ vmxnet3 ] Driver initializing (rev=0x1)
                [x] Device has 25 MSI-X vectors
                MSI-X vector 0 pointing to cpu 0 intr 64
                MSI-X vector 1 pointing to cpu 0 intr 65
                MSI-X vector 2 pointing to cpu 0 intr 66
    [ vmxnet3 ] Version 3.1
                MAC address: 00:0c:29:0f:ff:79
                Link up at 10000 Mbps
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                +--+ Other Bridge (0x4)
                |
                o
    [ Devices ] Listing registered devices
                |
                +--+ NIC
                |  + #0: eth0, driver vmxnet3
                |
                o
       [ CMOS ] RTC is 24 hour format, BCD mode
        [ RTC ] Enabling regular clock sync with CMOS
     [ Kernel ] Initializing plugins
================================================================================
 IncludeOS v0.10.0-rc.2-756-g11edfff2
 +--> Running [ VMWare Canary Test Service ]
 ```

**Comment by fwsGonzo** [comment] 2017-03-31 11:23
Not a bug, there are just lots of bridges.. if you want, you can just skip the output when the bridge has zero members. Closing.

**Closed by fwsGonzo** 2017-03-31 11:23 UTC
