### ISSUE TITLE
Building service with size-optimizations garbles memory

### ISSUE THREAD

**Issue by alfred-bratterud** [hioa-cs/IncludeOS#186] opened 2015-09-14 15:31 UTC
The size optimization flags `-Os` and `-Oz` flags causes aligniment errors (or something) when building the service. 
* Building `os.a` with these flags is fine, as long as the service is built without them
* Building `test_service.o` with these flags causes crazy behavior:
  * TCP object is suddenly in the wrong address, causing map emplacement to take forever etc.

Thoughts:
* Gnu `ld` doesn't play well with clang's size optimization?
* I noticed that *compiling* with `-flto` causes `ld` to say "unrecognized file format". Related?

**Comment by fwsGonzo** [comment] 2016-01-19 11:42
Was this fixed with explicit stack-realignment?

**Comment by fwsGonzo** [comment] 2016-01-19 17:07
Stripped worked for me on my laptop

**Comment by fwsGonzo** [comment] 2016-03-11 23:32
Can't reproduce this anymore, in any VMM with any combination of stripped and non-stripped service/kernel

**Closed by fwsGonzo** 2016-03-11 23:32 UTC
Labels: bug, Build
